//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_22_2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_cung_ung
    {
        public int so_phieu { get; set; }
        public string ma_hang_hoa { get; set; }
        public Nullable<int> so_luong { get; set; }
        public Nullable<double> thanh_tien { get; set; }
    
        public virtual hang_hoa hang_hoa { get; set; }
        public virtual phieu_cung_ung phieu_cung_ung { get; set; }
    }
}
