//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_22_2023.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DDBModel : DbContext
    {
        public DDBModel()
            : base("name=DDBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chi_tiet_cung_ung> chi_tiet_cung_ung { get; set; }
        public virtual DbSet<hang_hoa> hang_hoa { get; set; }
        public virtual DbSet<kha_nang> kha_nang { get; set; }
        public virtual DbSet<loai_hang_hoa> loai_hang_hoa { get; set; }
        public virtual DbSet<nha_cung_cap> nha_cung_cap { get; set; }
        public virtual DbSet<phieu_cung_ung> phieu_cung_ung { get; set; }
    }
}
