//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_22_2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hang_hoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hang_hoa()
        {
            this.chi_tiet_cung_ung = new HashSet<chi_tiet_cung_ung>();
        }
    
        public string ma_hang_hoa { get; set; }
        public string ten_hang_hoa { get; set; }
        public string quy_cach { get; set; }
        public string don_vi_tinh { get; set; }
        public Nullable<int> don_gia { get; set; }
        public string ma_loai_hang_hoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_cung_ung> chi_tiet_cung_ung { get; set; }
        public virtual loai_hang_hoa loai_hang_hoa { get; set; }
    }
}
