//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_22_2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loai_hang_hoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public loai_hang_hoa()
        {
            this.kha_nang = new HashSet<kha_nang>();
        }
    
        public string ma_loai_hang_hoa { get; set; }
        public string ten_loai_hang_hoa { get; set; }
        public string ghi_chu { get; set; }
        public string hinh_anh { get; set; }
    
        public virtual hang_hoa hang_hoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kha_nang> kha_nang { get; set; }
    }
}
