//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_22_2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieu_cung_ung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phieu_cung_ung()
        {
            this.chi_tiet_cung_ung = new HashSet<chi_tiet_cung_ung>();
        }
    
        public int so_phieu { get; set; }
        public Nullable<System.DateTime> ngay_thanh_lap { get; set; }
        public Nullable<double> tri_gia_phieu { get; set; }
        public string ma_nha_cung_cap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_cung_ung> chi_tiet_cung_ung { get; set; }
        public virtual nha_cung_cap nha_cung_cap { get; set; }
    }
}
